# NumPy

## Introduction to NumPy Arrays
Arrays are the main data structure used in machine learning. In Python, arrays from the NumPy library, called N-dimensional arrays or the ndarray, are used as the primary data structure for representing data.

### NumPy N-dimensional Array
NumPy is a Python library that can be used for scientific and numerical applications and is the tool to use for linear algebra operations. The main data structure in NumPy is the ndarray, which is a shorthand name for N-dimensional array. When working with NumPy, data in an ndarray is simply referred to as an array. It is a fixed-sized array in memory that contains data of the same type, such as integers or floating point values.

The data type supported by an array can be accessed via the dtype attribute on the array.
The dimensions of an array can be accessed via the shape attribute that returns a tuple
describing the length of each dimension.

In [1]:
# Create array
import numpy as np

l=[1.6,8.9,3.6,5.6]
arr=np.array(l)

# display array
print(arr)
# display array shape
print(arr.shape)
# array datatype
print(arr.dtype)

[1.6 8.9 3.6 5.6]
(4,)
float64


### Functions to Create Arrays

### Empty
The `empty()` function will create a new array of the specified shape. The argument to the
function is an array or tuple that specifies the length of each dimension of the array to create.The values or content of the created array will be random and will need to be assigned before use.

In [10]:
arr=np.empty(3)
print(arr)

[0.00000000e+000 2.12199579e-314 1.58101007e-322]


In [12]:
# arr=np.empty((3,4))
arr=np.empty([3,4])
print(arr)

[[2.0393923e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000]]


### Zeros
The `zeros()` function will create a new array of the specified size with the contents filled with zero values. The argument to the function is an array or tuple that specifies the length of each dimension of the array to create.

In [18]:
# create a zero array
arr=np.zeros(3)
# arr=np.zeros(3,)
# arr=np.zeros((3))
# arr=np.zeros((3,))
arr2=np.zeros([3,5])
print(arr)
print(arr2)

[0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


### Ones
The `ones()` function will create a new array of the specified size with the contents filled with one values. The argument to the function is an array or tuple that specifies the length of each dimension of the array to create.

In [19]:
arr=np.ones(5)
arr2=np.ones([4,6])
arr3=np.ones([2,3,4])
print(arr)
print(arr2)
print(arr3)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


### Combining Arrays
NumPy provides many functions to create new arrays from existing arrays.

### Vertical Stack
Given two or more existing arrays, you can stack them vertically using the `vstack()` function.

In [28]:
# create array with vstack

arr=np.array([1,2,3,4])
arr2=np.array([4,5,6,7])
arr3=np.vstack((arr,arr2))
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [4 5 6 7]]
(2, 4)


In [29]:
arr=np.array([[1,2,3,4],[1,2,3,4]])
arr2=np.array([[1,2,3,4],[1,2,3,4]])
arr3=np.vstack((arr,arr2))
print(arr3)
print(arr3.shape)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
(4, 4)


### Horizontal Stack
Given two or more existing arrays, you can stack them horizontally using the `hstack()` function.

In [31]:
arr=np.ones(5)
arr2=np.ones(5)
arr3=np.hstack((arr,arr2))
print(arr)
print(arr2)
print(arr3)
print(arr3.shape)

[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(10,)


In [41]:
arr=np.ones((5,5))
arr2=np.ones((5,5))
arr3=np.hstack((arr,arr2))
print(arr)
print(arr2)
print(arr3)
print(arr3.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
(5, 10)


In [45]:
arr=np.ones((5,5))
arr2=np.zeros((5,5))
arr3=np.hstack((arr,arr2))
print(arr)
print(arr2)
print(arr3)
print(arr3.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]]
(5, 10)


In [36]:
arr=np.zeros((5,5))
arr2=np.ones((5,5))
arr3=np.hstack((arr,arr2))
print(arr)
print(arr2)
print(arr3)
print(arr3.shape)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]]
(5, 10)


### One-Dimensional List to Array

In [46]:
data=[2,6,5,7,8,9,34,55]
arr=np.array(data)
print(arr)
print(type(arr))

[ 2  6  5  7  8  9 34 55]
<class 'numpy.ndarray'>


## List of Lists to Array

In [47]:
data=[[2,6,5,7,8,9,34,55],
     [2,6,5,7,8,9,34,55],
     [2,6,5,7,8,9,34,55]
     ]
arr=np.array(data)
print(arr)
print(type(arr))

[[ 2  6  5  7  8  9 34 55]
 [ 2  6  5  7  8  9 34 55]
 [ 2  6  5  7  8  9 34 55]]
<class 'numpy.ndarray'>


## Array Indexing
Once your data is represented using a NumPy array, you can access it using indexing.

### One-Dimensional Indexing

In [49]:
data=np.array([4,6,8,9,55,44])
# index data
print(data[0])
print(data[2])
print(data[-1])
print(data[-4])

4
8
44
8


### Two-Dimensional Indexing
Indexing two-dimensional data is similar to indexing one-dimensional data, except that a comma is used to separate the index for each dimension.

In [52]:
# define array
data = np.array([
[11, 22,33],
[33, 44,55],
[55, 66,77]])
# index data
print(data[0,0])

11


In [53]:
# index row of two-dimensional array
print(data[0,])

[11 22 33]


### One-Dimensional Slicing

In [57]:
# slice a one-dimensional array
data = np.array([11, 22, 33, 44, 55])
print(data[:])
print(data[2:4])

[11 22 33 44 55]
[33 44]


In [59]:
# negative slicing of a one-dimensional array
data = np.array([11, 22, 33, 44, 55])
print(data[-2:])

[44 55]


### Two-Dimensional Slicing

In [61]:
# split input and output data
data = np.array([
    [11, 22, 33,45],
    [44, 55, 66,75],
    [77, 88, 99,105]])

# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[ 45  75 105]


In [68]:
# split train and test data
data = np.array([
    [11, 22, 33,45],
    [44, 55, 66,75],
    [77, 88, 99,105],
    np.random.random(4),
     np.random.randn(4)
])
# separate data
split = 3
train,test = data[:split,:],data[split:,:]
print(train)
print(test)

[[ 11.  22.  33.  45.]
 [ 44.  55.  66.  75.]
 [ 77.  88.  99. 105.]]
[[ 0.23727559  0.90116729  0.04527181  0.3934552 ]
 [-1.15902711  0.81905649  0.45377084  0.44511357]]


## Array Reshaping

### Data Shape
NumPy arrays have a shape attribute that returns a tuple of the length of each dimension of
the array. For example:

In [70]:
# shape of one-dimensional array
data=np.random.randn(5)
print(data.shape)

(5,)


In [73]:
# shape of two-dimensional array
data=np.array([np.random.randn(5),
      np.random.randn(5),
      np.random.randn(5)])
print(data.shape)

(3, 5)


In [74]:
# row and column shape of two-dimensional array
data = np.array([
    np.random.randn(5),
    np.random.randn(5),
    np.random.randn(5)
])
print( ' Rows: %d ' % data.shape[0])
print( ' Cols: %d ' % data.shape[1])

 Rows: 3 
 Cols: 5 


### Reshape 1D to 2D Array

In [78]:
# reshape 1D array to 2D
data = np.array([11, 22, 33, 44, 55,66,77,88])
print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data)
print(data.shape)

[11 22 33 44 55 66 77 88]
(8,)
[[11]
 [22]
 [33]
 [44]
 [55]
 [66]
 [77]
 [88]]
(8, 1)


### Reshape 2D to 3D Array

In [80]:
# reshape 2D array to 3D
data=np.random.random((2,3))
print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data)
print(data.shape)

[[0.48796968 0.27820108 0.12555154]
 [0.39348364 0.29872044 0.04114748]]
(2, 3)
[[[0.48796968]
  [0.27820108]
  [0.12555154]]

 [[0.39348364]
  [0.29872044]
  [0.04114748]]]
(2, 3, 1)


### # reshape 3D to 4D array

In [82]:
# reshape 3D array to 4D
data=np.random.random((2,3,3))
print(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1],data.shape[2], 1))
print(data)
print(data.shape)

[[[0.56042289 0.1249554  0.25889058]
  [0.20462487 0.06564403 0.06969129]
  [0.80124299 0.07694329 0.3365229 ]]

 [[0.39711319 0.24904178 0.89131716]
  [0.82260919 0.03247181 0.17578672]
  [0.89642845 0.97737841 0.0741536 ]]]
(2, 3, 3)
[[[[0.56042289]
   [0.1249554 ]
   [0.25889058]]

  [[0.20462487]
   [0.06564403]
   [0.06969129]]

  [[0.80124299]
   [0.07694329]
   [0.3365229 ]]]


 [[[0.39711319]
   [0.24904178]
   [0.89131716]]

  [[0.82260919]
   [0.03247181]
   [0.17578672]]

  [[0.89642845]
   [0.97737841]
   [0.0741536 ]]]]
(2, 3, 3, 1)


## NumPy Array Broadcasting
Arrays with different sizes cannot be added, subtracted, or generally be used in arithmetic. A way to overcome this is to duplicate the smaller array so that it has the dimensionality and size as the larger array. This is called array broadcasting and is available in NumPy when performing array arithmetic.

### Scalar and One-Dimensional Array
A single value or scalar can be used in arithmetic with a one-dimensional array.

In [84]:
# broadcast scalar to one-dimensional array
from numpy import array
# define array
a = array([1, 2, 3,4,5])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3 4 5]
2
[3 4 5 6 7]


## Scalar and Two-Dimensional Array
A scalar value can be used in arithmetic with a two-dimensional array.

In [85]:
# broadcast scalar to two-dimensional array
A=np.random.random((3,4))
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)

[[0.21242801 0.22299696 0.22690196 0.51090362]
 [0.32349611 0.4440564  0.36836489 0.47745511]
 [0.26076767 0.19656505 0.98632904 0.08219226]]
2
[[2.21242801 2.22299696 2.22690196 2.51090362]
 [2.32349611 2.4440564  2.36836489 2.47745511]
 [2.26076767 2.19656505 2.98632904 2.08219226]]


### One-Dimensional and Two-Dimensional Arrays
A one-dimensional array can be used in arithmetic with a two-dimensional array. For example, we can imagine a two-dimensional array A with 2 rows and 3 columns added to a one-dimensional array b with 3 values.

In [90]:
A=np.random.random((3,4))
print(A)
# define one-dimensional array
b = np.ones(4)
print(b)
# broadcast
C = A + b
print(C)

[[0.13768286 0.34503133 0.35702293 0.27597146]
 [0.75644295 0.62547429 0.01241609 0.05387875]
 [0.17133453 0.48311501 0.76920716 0.28087717]]
[1. 1. 1. 1.]
[[1.13768286 1.34503133 1.35702293 1.27597146]
 [1.75644295 1.62547429 1.01241609 1.05387875]
 [1.17133453 1.48311501 1.76920716 1.28087717]]


In [92]:
# broadcasting error
# A = array([
#     [1, 2, 3],
#     [1, 2, 3]])
# print(A.shape)
# define one-dimensional array
# b = array([1, 2])
# print(b.shape)
# attempt broadcast
# C = A + b
# print(C)